name: Ensure all rules are everywhere
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - ready_for_review

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2.4.0

      - name: Set up Node.js
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 14.x

      - name: Install npm dependencies
        run: npm install

      - name: Ensure all rules are in the README
        run: npx markdownlint README.md docs/README.md --config tests/docs/.markdownlint.json --rules tests/docs/README.js

      - name: Ensure all rules are documented
        run: |
          passes=true
          for rule in $(ls lib/rules | sed 's/\.js$//')
          do
            if [ ! -f "docs/rules/$rule.md" ]
            then
              passes=false
              echo "Expected documentation for $rule to exist"
            fi
          done
          if [ ! "$passes" = true ]
          then
            exit 1
          fi
      - name: Ensure all rules are in the documentation sidebar
        run: npx markdownlint docs/_sidebar.md --config tests/docs/.markdownlint.json --rules tests/docs/_sidebar.js
