name: Publish

on:
  release:
    types: [published, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2.4.0

      - name: Set up Node.js
        uses: actions/setup-node@v3.0.0
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org/

      - name: Install npm dependencies
        run: npm install

      - name: Publish Package
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
