name: Ensure both READMEs are synced
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - ready_for_review

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2.3.5

      - name: Set up Node.js
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 14.x

      - name: Install npm dependencies
        run: npm install

      - name: Copy Documentation README
        run: ./.husky/pre-commit

      - name: Ensure there is no Git Changes
        run: |
          if [ -z "$(git status --short)" ]
          then
            echo "README.md and docs/README.md are in sync"
          else
            echo "Make sure that the README.md and docs/README.md are in sync"
            exit 1
          fi
